# Generated by Django 6.1.1 on 2026-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tipologjia', models.CharField(choices=[('A', 'Tipologjia A'), ('B', 'Tipologjia B'), ('C', 'Tipologjia C')], max_length=1)),
                ('surface_area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('has_pool', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
